### ISSUE TITLE
Decode error

### ISSUE THREAD

**Issue by wadewegner** [sindresorhus/get-urls#15]
The presence of  `).{%` trailing a valid URL (e.g. `http://cnn.com/).{%`) causes the error:

```
[PATH]/node_modules/normalize-url/index.js:82
		urlObj.pathname = decodeURI(urlObj.pathname);
		                  ^

URIError: URI malformed
    at decodeURI (native)
    at module.exports ([PATH]/node_modules/normalize-url/index.js:82:21)
    at [PATH]/node_modules/get-urls/index.js:14:10
    at Array.map (native)
    at module.exports ([PATH]/node_modules/get-urls/index.js:13:24)
    at [PATH]/index.js:17:16
    at Array.forEach (native)
    at [PATH]/index.js:15:9
    at [PATH]/node_modules/recursive-readdir/index.js:64:22
    at [PATH]/node_modules/recursive-readdir/index.js:64:22
```

**Comment by sindresorhus** [comment]
The problem is with https://github.com/kevva/url-regex, which picks up `http://cnn.com/).{%` as an URL. Open an issue there ;)
